
# github link : https://github.com/binalbariya/Data-Warehousing/blob/main/Assesment%201.ipynb

# Basic data structures


# List  
Lists are used to store data of different data types in a sequential manner.

In [1]:
#Creating a list
my_list = [] #create empty list
print(my_list)
my_list = ["20MAI0075", 2, "binal", 'example', 3.132] #creating list with data
print(my_list)
print(type(my_list))

[]
['20MAI0075', 2, 'binal', 'example', 3.132]
<class 'list'>


In [2]:
#Adding elements to the list
my_list = [1, 2, 3]
print(my_list)
my_list.append([35, 26]) #add as a single element
print(my_list)
my_list.extend([234, 'more_content']) #add as different elements
print(my_list)
my_list.insert(2, 'insert_content') #add element i
print(my_list)

[1, 2, 3]
[1, 2, 3, [35, 26]]
[1, 2, 3, [35, 26], 234, 'more_content']
[1, 2, 'insert_content', 3, [35, 26], 234, 'more_content']


In [3]:
#deleting elements from the list
my_list = [1, 2, 3, 'example', 3.132, 10, 30]
del my_list[5] #delete element at index 5
print(my_list)
my_list.remove('example') #remove element with value
print(my_list)
a = my_list.pop(1) #pop element from list
print('Popped Element: ', a, ' List remaining: ', my_list)
my_list.clear() #empty the list
print(my_list)

[1, 2, 3, 'example', 3.132, 30]
[1, 2, 3, 3.132, 30]
Popped Element:  2  List remaining:  [1, 3, 3.132, 30]
[]


In [4]:
#Accessing Elements
my_list = [1, 2, 3, 'example', 3.132, 10, 30]
for element in my_list: #access elements one by one
    print(element)
print(my_list) #access all elements
print(my_list[3]) #access index 3 element
print(my_list[0:2]) #access elements from 0 to 1 and exclude 2
print(my_list[::-1]) #access elements in reverse

1
2
3
example
3.132
10
30
[1, 2, 3, 'example', 3.132, 10, 30]
example
[1, 2]
[30, 10, 3.132, 'example', 3, 2, 1]


In [5]:
#other extra functions

my_list = [1, 2, 3, 10, 30, 10]
print(len(my_list)) #find length of list
print(my_list.index(10)) #find index of element that occurs first
print(my_list.count(10)) #find count of the element
print(sorted(my_list)) #print sorted list but not change original
my_list.sort(reverse=True) #sort original list
print(my_list)

6
3
2
[1, 2, 3, 10, 10, 30]
[30, 10, 10, 3, 2, 1]


# Dictionary
Dictionaries are used to store key-value pairs.

In [6]:
#Creating a dictionary
my_dict = {} #empty dictionary
print(my_dict)
my_dict = {1: 'Python', 2: 'Java'} #dictionary with elements
print(my_dict)

{}
{1: 'Python', 2: 'Java'}


In [7]:
#Changing and adding key value pairs

my_dict = {'First': 'Python', 'Second': 'Java'}
print(my_dict)
my_dict['Second'] = 'C++' #changing element
print(my_dict)
my_dict['Third'] = 'Ruby' #adding key-value pair
print(my_dict)

{'First': 'Python', 'Second': 'Java'}
{'First': 'Python', 'Second': 'C++'}
{'First': 'Python', 'Second': 'C++', 'Third': 'Ruby'}


In [8]:
#deleting key value pairs

my_dict = {'First': 'Python', 'Second': 'Java', 'Third': 'Ruby'}
a = my_dict.pop('Third') #pop element
print('Value:', a)
print('Dictionary:', my_dict)
b = my_dict.popitem() #pop the key-value pair
print('Key, value pair:', b)
print('Dictionary', my_dict)
my_dict.clear() #empty dictionary
print('n', my_dict)

Value: Ruby
Dictionary: {'First': 'Python', 'Second': 'Java'}
Key, value pair: ('Second', 'Java')
Dictionary {'First': 'Python'}
n {}


In [9]:
#Accessing elements

my_dict = {'First': 'Python', 'Second': 'Java'}
print(my_dict['First']) #access elements using keys
print(my_dict.get('Second'))

Python
Java


In [10]:
#Other functions

my_dict = {'First': 'Python', 'Second': 'Java', 'Third': 'Ruby'}
print(my_dict.keys()) #get keys
print(my_dict.values()) #get values
print(my_dict.items()) #get key-value pairs
print(my_dict.get('First'))

dict_keys(['First', 'Second', 'Third'])
dict_values(['Python', 'Java', 'Ruby'])
dict_items([('First', 'Python'), ('Second', 'Java'), ('Third', 'Ruby')])
Python


# Tuple
Tuples are the same as lists are with the exception that the data once entered into the tuple cannot be changed no matter what. 

In [11]:
#Creating a tuple

my_tuple = (1, 2, 3) #create tuple
print(my_tuple) 

(1, 2, 3)


In [12]:
#Acesing elements
my_tuple2 = (1, 2, 3, 'binal') #access elements
for x in my_tuple2:
    print(x)
print(my_tuple2)
print(my_tuple2[0])
print(my_tuple2[:])
print(my_tuple2[3][4])

1
2
3
binal
(1, 2, 3, 'binal')
1
(1, 2, 3, 'binal')
l


In [13]:
#Adding elements

my_tuple = (1, 2, 3)
my_tuple = my_tuple + (4, 5, 6) #add elements
print(my_tuple)

(1, 2, 3, 4, 5, 6)


In [14]:
#Other functions

my_tuple = (1, 2, 3, ['hindi', 'python'])
my_tuple[3][0] = 'english'
print(my_tuple)
print(my_tuple.count(2))
print(my_tuple.index(['english', 'python']))

(1, 2, 3, ['english', 'python'])
1
3


# Sets
Sets are a collection of unordered elements that are unique. Meaning that even if the data is repeated more than one time, it would be entered into the set only once.

In [15]:
#Creating a set

my_set = {1, 2, 3, 4, 5, 5, 5} #create set
print(my_set)

{1, 2, 3, 4, 5}


In [16]:
#Adding elements

my_set = {1, 2, 3}
my_set.add(4) #add element to set
print(my_set)

{1, 2, 3, 4}


In [17]:
# Operations on sets

my_set = {1, 2, 3, 4}
my_set_2 = {3, 4, 5, 6}
print(my_set.union(my_set_2), '----------', my_set | my_set_2)
print(my_set.intersection(my_set_2), '----------', my_set & my_set_2)
print(my_set.difference(my_set_2), '----------', my_set - my_set_2)
print(my_set.symmetric_difference(my_set_2), '----------', my_set ^ my_set_2)
my_set.clear()
print(my_set)

{1, 2, 3, 4, 5, 6} ---------- {1, 2, 3, 4, 5, 6}
{3, 4} ---------- {3, 4}
{1, 2} ---------- {1, 2}
{1, 2, 5, 6} ---------- {1, 2, 5, 6}
set()


# Numpy
NumPy stands for Numerical Python. It is a Python library used for working with an array. In Python, we use the list for purpose of the array but it’s slow to process.

In [18]:
import numpy as np
print(np.__version__)

1.19.1


In [20]:
# importing numpy module 
import numpy as np 
  
# creating list  
list = [1, 2, 3, 4] 
  
# creating numpy array 
sample_array = np.array(list) 
  
print("List in python : ", list) 
  
print("Numpy Array in python :", 
      sample_array)

List in python :  [1, 2, 3, 4]
Numpy Array in python : [1 2 3 4]


In [21]:
#Checking data type of list and array

print(type(list)) 
  
print(type(sample_array))

<class 'list'>
<class 'numpy.ndarray'>


In [22]:
#Multi dimensional array

# creating list  
list_1 = [1, 2, 3, 4] 
list_2 = [5, 6, 7, 8] 
list_3 = [9, 10, 11, 12] 
  
# creating numpy array 
sample_array = np.array([list_1,  
                         list_2, 
                         list_3]) 
  
print("Numpy multi dimensional array in python\n", 
      sample_array)

Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
#shape

print("Numpy array :") 
print(sample_array) 
  
# print shape of the array 
print("Shape of the array :", 
      sample_array.shape)

Numpy array :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of the array : (3, 4)


In [41]:
arr = np.array([[0, 4, 2], 
                       [3, 4, 5], 
                       [23, 4, 5], 
                       [2, 34, 5], 
                       [5, 6, 7]]) 
  
print("shape of the array :", 
      arr.shape)

# Printing type of arr object 
print("Array is of type: ", type(arr)) 
  
# Printing array dimensions (axes) 
print("No. of dimensions: ", arr.ndim) 
    
# Printing size (total number of elements) of array 
print("Size of array: ", arr.size) 
  
# Printing type of elements in array 
print("Array stores elements of type: ", arr.dtype) 

shape of the array : (5, 3)
Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Size of array:  15
Array stores elements of type:  int32


In [25]:
# Creating the array  
sample_array_1 = np.array([[0, 4, 2]]) 
  
sample_array_2 = np.array([0.2, 0.4, 2.4]) 
  
# display data type 
print("Data type of the array 1 :", 
      sample_array_1.dtype) 
  
print("Data type of array 2 :", 
      sample_array_2.dtype)

Data type of the array 1 : int32
Data type of array 2 : float64


In [30]:
#Array can also be created as
  
arr = np.array([3,4,5,5]) 
  
print("Array :",arr)

Array : [3 4 5 5]


In [31]:
#  numpy.fromiter(): The fromiter() function create a new one-dimensional array from an iterable object.

# iterable 
iterable = (a*a for a in range(8)) 
  
arr = np.fromiter(iterable, float) 
  
print("fromiter() array :",arr)

fromiter() array : [ 0.  1.  4.  9. 16. 25. 36. 49.]


In [32]:
var = "Geekforgeeks"
  
arr = np.fromiter(var, dtype = 'U2') 
  
print("fromiter() array :", 
      arr)

fromiter() array : ['G' 'e' 'e' 'k' 'f' 'o' 'r' 'g' 'e' 'e' 'k' 's']


In [33]:
#  numpy.arange(): This is an inbuilt NumPy function that returns evenly spaced values within a given interval.

np.arange(1, 20 , 2,  
          dtype = np.float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

In [35]:
# numpy.linspace(): This function returns evenly spaced numbers over a specified between two limits.

np.linspace(3.5, 40, 3)

array([ 3.5 , 21.75, 40.  ])

In [36]:
np.linspace(3.5, 10, 3,  
            dtype = np.int32)

array([ 3,  6, 10])

In [37]:
# numpy.empty(): This function create a new array of given shape and type, without initializing value.

np.empty([4, 3], 
         dtype = np.int32, 
         order = 'f')

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [38]:
# numpy.ones(): This function is used to get a new array of given shape and type, filled with ones(1).

np.ones([4, 3], 
        dtype = np.int32, 
        order = 'f')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [39]:
#numpy.zeros(): This function is used to get a new array of given shape and type, filled with zeros(0).

np.zeros([4, 3],  
         dtype = np.int32, 
         order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Pandas


In [43]:
import pandas as pd
print(pd.__version__)

1.1.3


In [44]:
# Creating a Series by passing a list of values, letting pandas create a default integer index:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [46]:
# Creating a DataFrame by passing a NumPy array, with a datetime index and labeled columns:

dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [50]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=["A","B","C","D"])
df

A         B         C         D
2013-01-01  0.203897 -0.527945 -1.053923  1.330420
2013-01-02  1.789702  0.399927  0.690118  1.088212
2013-01-03  0.475112 -0.635497  0.594416  0.395118
2013-01-04  0.630971 -1.776335 -0.487059 -0.963542
2013-01-05  1.221116  1.344814  0.909924  0.382799
2013-01-06  1.076815 -0.775511  1.254177 -0.827070

In [52]:
df2 = pd.DataFrame({
"A": 1.0,
"B": pd.Timestamp("20130102"),
"C": pd.Series(1, index=[0,1,2,3], dtype="float32"),
"D": np.array([3] * 4, dtype="int32"),
"E": pd.Categorical(["test", "train", "test", "train"]),
"F": "foo",
})

In [53]:
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [55]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

dataframe = pd.read_csv("csv file location")

In [57]:
# Viewing the data

df.head()

A         B         C         D
2013-01-01  0.203897 -0.527945 -1.053923  1.330420
2013-01-02  1.789702  0.399927  0.690118  1.088212
2013-01-03  0.475112 -0.635497  0.594416  0.395118
2013-01-04  0.630971 -1.776335 -0.487059 -0.963542
2013-01-05  1.221116  1.344814  0.909924  0.382799

In [58]:
df.tail(3)

A         B         C         D
2013-01-04  0.630971 -1.776335 -0.487059 -0.963542
2013-01-05  1.221116  1.344814  0.909924  0.382799
2013-01-06  1.076815 -0.775511  1.254177 -0.827070

In [59]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [60]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [61]:
df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2013-01-01 to 2013-01-06
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes


In [63]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.899602 -0.328425  0.317942  0.234323
std    0.576787  1.073374  0.891288  0.952879
min    0.203897 -1.776335 -1.053923 -0.963542
25%    0.514077 -0.740508 -0.216690 -0.524603
50%    0.853893 -0.581721  0.642267  0.388958
75%    1.185041  0.167959  0.854973  0.914939
max    1.789702  1.344814  1.254177  1.330420

In [64]:
#DataFrame.to_numpy() gives a NumPy representation of the underlying data.

df.to_numpy()

array([[ 0.20389664, -0.52794493, -1.05392291,  1.33042049],
       [ 1.7897021 ,  0.39992695,  0.69011813,  1.08821232],
       [ 0.47511184, -0.63549703,  0.59441614,  0.39511825],
       [ 0.63097057, -1.77633518, -0.48705908, -0.96354183],
       [ 1.22111623,  1.34481365,  0.90992446,  0.38279859],
       [ 1.0768148 , -0.77551141,  1.25417737, -0.82707048]])

In [65]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [67]:
#Transpose of a dataset
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.203897    1.789702    0.475112    0.630971    1.221116    1.076815
B   -0.527945    0.399927   -0.635497   -1.776335    1.344814   -0.775511
C   -1.053923    0.690118    0.594416   -0.487059    0.909924    1.254177
D    1.330420    1.088212    0.395118   -0.963542    0.382799   -0.827070

In [68]:
# Sorting by an aaxis

df.sort_index(axis=1, ascending=False)

D         C         B         A
2013-01-01  1.330420 -1.053923 -0.527945  0.203897
2013-01-02  1.088212  0.690118  0.399927  1.789702
2013-01-03  0.395118  0.594416 -0.635497  0.475112
2013-01-04 -0.963542 -0.487059 -1.776335  0.630971
2013-01-05  0.382799  0.909924  1.344814  1.221116
2013-01-06 -0.827070  1.254177 -0.775511  1.076815

In [70]:
#Sorting by values

df.sort_values(by="B")


A         B         C         D
2013-01-04  0.630971 -1.776335 -0.487059 -0.963542
2013-01-06  1.076815 -0.775511  1.254177 -0.827070
2013-01-03  0.475112 -0.635497  0.594416  0.395118
2013-01-01  0.203897 -0.527945 -1.053923  1.330420
2013-01-02  1.789702  0.399927  0.690118  1.088212
2013-01-05  1.221116  1.344814  0.909924  0.382799

In [71]:
#SELECTION

df["A"]

2013-01-01    0.203897
2013-01-02    1.789702
2013-01-03    0.475112
2013-01-04    0.630971
2013-01-05    1.221116
2013-01-06    1.076815
Freq: D, Name: A, dtype: float64

In [72]:
df[0:3]

A         B         C         D
2013-01-01  0.203897 -0.527945 -1.053923  1.330420
2013-01-02  1.789702  0.399927  0.690118  1.088212
2013-01-03  0.475112 -0.635497  0.594416  0.395118

In [73]:
df["20130102":"20130104"]

A         B         C         D
2013-01-02  1.789702  0.399927  0.690118  1.088212
2013-01-03  0.475112 -0.635497  0.594416  0.395118
2013-01-04  0.630971 -1.776335 -0.487059 -0.963542

In [74]:
#selecting by label

df.loc[dates[0]]

A    0.203897
B   -0.527945
C   -1.053923
D    1.330420
Name: 2013-01-01 00:00:00, dtype: float64

In [75]:
df.loc[:, ["A", "B"]]

A         B
2013-01-01  0.203897 -0.527945
2013-01-02  1.789702  0.399927
2013-01-03  0.475112 -0.635497
2013-01-04  0.630971 -1.776335
2013-01-05  1.221116  1.344814
2013-01-06  1.076815 -0.775511

In [76]:
df.loc["20130102":"20130104", ["A", "B"]]

A         B
2013-01-02  1.789702  0.399927
2013-01-03  0.475112 -0.635497
2013-01-04  0.630971 -1.776335

In [77]:
df.loc[dates[0], "A"]

0.20389663711251033

In [78]:
df.at[dates[0], "A"]

0.20389663711251033

In [79]:
# Selection by postiiton

df.iloc[3]

A    0.630971
B   -1.776335
C   -0.487059
D   -0.963542
Name: 2013-01-04 00:00:00, dtype: float64

In [80]:
df.iloc[3:5, 0:2]

A         B
2013-01-04  0.630971 -1.776335
2013-01-05  1.221116  1.344814

In [87]:
#Missing data

df1 = df.reindex(index=dates[0:4], columns=['A','B','C','D','E'] + ["E"])
df1.loc[dates[0] : dates[1], "E"] = 1

df1

A         B         C         D    E    E
2013-01-01  0.203897 -0.527945 -1.053923  1.330420  1.0  1.0
2013-01-02  1.789702  0.399927  0.690118  1.088212  1.0  1.0
2013-01-03  0.475112 -0.635497  0.594416  0.395118  NaN  NaN
2013-01-04  0.630971 -1.776335 -0.487059 -0.963542  NaN  NaN

In [88]:
#to drop rows having missing data

df1.dropna(how="any")

A         B         C         D    E    E
2013-01-01  0.203897 -0.527945 -1.053923  1.330420  1.0  1.0
2013-01-02  1.789702  0.399927  0.690118  1.088212  1.0  1.0

In [89]:
#filling missing data

df1.fillna(value=5)

A         B         C         D    E    E
2013-01-01  0.203897 -0.527945 -1.053923  1.330420  1.0  1.0
2013-01-02  1.789702  0.399927  0.690118  1.088212  1.0  1.0
2013-01-03  0.475112 -0.635497  0.594416  0.395118  5.0  5.0
2013-01-04  0.630971 -1.776335 -0.487059 -0.963542  5.0  5.0

In [90]:
pd.isna(df1)

A      B      C      D      E      E
2013-01-01  False  False  False  False  False  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False   True   True
2013-01-04  False  False  False  False   True   True

In [91]:
pd.isna(df1).sum()

A    0
B    0
C    0
D    0
E    2
E    2
dtype: int64

In [92]:
df.mean()

A    0.899602
B   -0.328425
C    0.317942
D    0.234323
dtype: float64

In [94]:
#Grouping of data 
df.groupby("A").sum()

B         C         D
A                                     
0.203897 -0.527945 -1.053923  1.330420
0.475112 -0.635497  0.594416  0.395118
0.630971 -1.776335 -0.487059 -0.963542
1.076815 -0.775511  1.254177 -0.827070
1.221116  1.344814  0.909924  0.382799
1.789702  0.399927  0.690118  1.088212

In [95]:
df.groupby(["A", "B"]).sum()

C         D
A        B                            
0.203897 -0.527945 -1.053923  1.330420
0.475112 -0.635497  0.594416  0.395118
0.630971 -1.776335 -0.487059 -0.963542
1.076815 -0.775511  1.254177 -0.827070
1.221116  1.344814  0.909924  0.382799
1.789702  0.399927  0.690118  1.088212